set(MiniSat_VERSION git)
get_filename_component(MiniSat_DIR ${CMAKE_CURRENT_LIST_FILE} PATH)
set(MiniSat_BIN_DIRS     ${MiniSat_DIR}/bin )
set(MiniSat_INCLUDE_DIRS ${MiniSat_DIR}/include )
set(MiniSat_INCLUDE_DIR  ${MiniSat_INCLUDE_DIRS} )
if (APPLE)
   set(MiniSat_LIBRARIES    ${MiniSat_DIR}/lib/libminisat.dylib )
else()
   set(MiniSat_LIBRARIES    ${MiniSat_DIR}/lib/libminisat.so )
endif()

if(APPLE)
  set(CMAKE_C_COMPILER clang)
  set(CMAKE_CXX_COMPILER clang++)
else()
  set(CMAKE_C_COMPILER /usr/bin/gcc-4.9)
  set(CMAKE_CXX_COMPILER /usr/bin/g++-4.9)
endif()
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

message("The compiler is now ${CMAKE_CXX_COMPILER}.")

set(MiniSat_CXXFLAGS     "-D__STDC_LIMIT_MACROS -D__STDC_FORMAT_MACROS")
